/**
 * Copyright (c) OWOX, Inc.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

var FacebookPagesFieldsSchema = {
  page_insights_daily: {
    overview: 'Facebook Page Insights',
    description: 'Daily organic metrics for one Facebook Page.',
    documentation: 'https://developers.facebook.com/docs/graph-api/reference/page/insights/',
    fields: pageInsightsFields,
    uniqueKeys: ['page_id', 'date_start', 'date_stop'],
    defaultFields: [
      'page_id',
      'page_name',
      'date_start',
      'date_stop',
      'page_views_total',
      'page_post_engagements',
      'page_follows',
    ],
    destinationName: 'facebook_pages_page_insights_daily',
    isTimeSeries: true,
  },
  page_profile: {
    overview: 'Facebook Page profile metadata',
    description: 'Current profile metadata for each selected Facebook Page.',
    documentation: 'https://developers.facebook.com/docs/graph-api/reference/page/',
    fields: pageProfileFields,
    uniqueKeys: ['page_id'],
    defaultFields: [
      'page_id',
      'page_name',
      'category',
      'fan_count',
      'followers_count',
      'link',
      'about',
      'instagram_business_account_id',
      'fetched_at',
    ],
    destinationName: 'facebook_pages_page_profile',
    isTimeSeries: false,
  },
  page_posts_insights_daily: {
    overview: 'Facebook Page post insights',
    description: 'Daily insights for posts published on selected Facebook Pages.',
    documentation: 'https://developers.facebook.com/docs/graph-api/reference/post/insights/',
    fields: pagePostInsightsFields,
    uniqueKeys: ['page_id', 'post_id', 'date_start', 'date_stop'],
    defaultFields: [
      'page_id',
      'post_id',
      'post_message',
      'post_created_time',
      'permalink_url',
      'date_start',
      'date_stop',
      'post_engaged_users',
      'post_clicks',
      'post_reactions',
    ],
    destinationName: 'facebook_pages_page_posts_insights_daily',
    isTimeSeries: true,
  },
  page_videos_insights_daily: {
    overview: 'Facebook Page video insights',
    description: 'Daily insights for videos published on selected Facebook Pages.',
    documentation: 'https://developers.facebook.com/docs/graph-api/reference/video/insights/',
    fields: pageVideoInsightsFields,
    uniqueKeys: ['page_id', 'video_id', 'date_start', 'date_stop'],
    defaultFields: [
      'page_id',
      'video_id',
      'video_title',
      'video_created_time',
      'permalink_url',
      'date_start',
      'date_stop',
      'total_video_views',
      'total_video_10s_views',
      'total_video_30s_views',
    ],
    destinationName: 'facebook_pages_page_videos_insights_daily',
    isTimeSeries: true,
  },
  instagram_account_insights_daily: {
    overview: 'Instagram account insights linked to Facebook Page',
    description: 'Daily account-level insights for the linked Instagram professional account.',
    documentation: 'https://developers.facebook.com/docs/instagram-api/reference/ig-user/insights/',
    fields: instagramAccountInsightsFields,
    uniqueKeys: ['page_id', 'instagram_account_id', 'date_start', 'date_stop'],
    defaultFields: [
      'page_id',
      'instagram_account_id',
      'instagram_username',
      'date_start',
      'date_stop',
      'impressions',
      'reach',
      'profile_views',
      'website_clicks',
    ],
    destinationName: 'facebook_pages_instagram_account_insights_daily',
    isTimeSeries: true,
  },
  instagram_media_insights_daily: {
    overview: 'Instagram media insights linked to Facebook Page',
    description: 'Daily insights for Instagram media published by the linked account.',
    documentation:
      'https://developers.facebook.com/docs/instagram-api/reference/ig-media/insights/',
    fields: instagramMediaInsightsFields,
    uniqueKeys: ['page_id', 'instagram_media_id', 'date_start', 'date_stop'],
    defaultFields: [
      'page_id',
      'instagram_media_id',
      'media_type',
      'caption',
      'media_timestamp',
      'date_start',
      'date_stop',
      'impressions',
      'reach',
      'engagement',
      'saves',
      'comments',
      'likes',
    ],
    destinationName: 'facebook_pages_instagram_media_insights_daily',
    isTimeSeries: true,
  },
  page_audience_breakdown_daily: {
    overview: 'Facebook Page audience breakdowns',
    description: 'Daily age, gender, country and city audience breakdowns returned by Meta.',
    documentation: 'https://developers.facebook.com/docs/graph-api/reference/page/insights/',
    fields: pageAudienceBreakdownFields,
    uniqueKeys: ['page_id', 'date_start', 'date_stop', 'breakdown', 'dimension_value'],
    defaultFields: [
      'page_id',
      'date_start',
      'date_stop',
      'breakdown',
      'dimension_value',
      'metric_value',
    ],
    destinationName: 'facebook_pages_page_audience_breakdown_daily',
    isTimeSeries: true,
  },
};
